// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkawpsjlbxvacbgnrivb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrYXdwc2psYnh2YWNiZ25yaXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1Mjk3OTYsImV4cCI6MjA3NjEwNTc5Nn0.YsKqX8xs6p1lfhSEi9U-FyMjBGkM68Sf0tZc4qDIGYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});